-- 想去 / 去过标记表
-- 在 Supabase Dashboard → SQL Editor 执行一次即可。
-- 用户可对「花卉 / 赏花景点 / 人文建筑」标记 想去(wish) 或 去过(visited)，与成就系统联动。

create table if not exists public.marks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  target_type text not null check (target_type in ('flower', 'spot', 'building')),
  target_key text not null,
  status text not null check (status in ('wish', 'visited')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, target_type, target_key)
);

alter table public.marks enable row level security;

create policy "marks_select_own"
  on public.marks for select
  using (auth.uid() = user_id);

create policy "marks_insert_own"
  on public.marks for insert
  with check (auth.uid() = user_id);

create policy "marks_update_own"
  on public.marks for update
  using (auth.uid() = user_id);

create policy "marks_delete_own"
  on public.marks for delete
  using (auth.uid() = user_id);
